# Generated by Django 4.2.5 on 2023-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address_address_unique_primary_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
