# Generated by Django 4.2.5 on 2023-12-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_vendor_store_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-set_primary']},
        ),
    ]
