# Generated by Django 4.2.5 on 2023-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_slug_alter_item_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tag1',
            field=models.CharField(default='tag', max_length=100),
        ),
    ]
