# Generated by Django 4.2.5 on 2023-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_discount_item_tag1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(default='tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.TextField(default='tag', max_length=200),
        ),
    ]
