# Generated by Django 4.2.5 on 2023-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.CharField(default='tag', max_length=200),
        ),
    ]
