# Generated by Django 4.2.5 on 2023-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_item_tag1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag1',
            field=models.CharField(max_length=200),
        ),
    ]
