# Generated by Django 4.2.5 on 2023-12-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_item_tag1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag1',
        ),
    ]
