# Generated by Django 4.2.5 on 2023-12-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_deliveryprice_item_color_item_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryPrice',
            new_name='DeliveryCharges',
        ),
    ]
