# Generated by Django 4.2.5 on 2023-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_deliveryprice_deliverycharges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCharges',
        ),
    ]
