# Generated by Django 4.2.5 on 2023-12-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default='self.price', max_digits=8),
        ),
    ]
