# Generated by Django 4.2.5 on 2023-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
