# Generated by Django 4.2.5 on 2023-12-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_discounted_price',
            field=models.FloatField(),
        ),
    ]
