# Generated by Django 4.2.5 on 2023-12-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_image',
            field=models.ImageField(default='images/image.png', upload_to=''),
        ),
    ]
