# Generated by Django 4.2.5 on 2023-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Order Shipped', 'Order Shipped'), ('Order Cancelled', 'Order Cancelled')], default='Order Placed', max_length=50),
        ),
    ]
