# Generated by Django 4.2.5 on 2023-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
