# Generated by Django 4.2.5 on 2023-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
