# Generated by Django 4.2.5 on 2023-12-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_item_discounted_price'),
        ('order', '0011_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.item'),
        ),
    ]
